/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.msmanagement;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 * @author ramki
 */
public class GenBill extends javax.swing.JFrame {

    /**
     * Creates new form Test1
     */
    private static ArrayList al ;
    private static String[] arr ;

    Connection conn;    
    public GenBill() {
        
        //jPanel4.setVisible(false);
        getMedicine();
        arr=new String[al.size()];
            al.toArray(arr);
            initComponents();
            jPanel4.setVisible(false);
            jPanel5.setVisible(false);
            jPanel6.setVisible(false);
            jPanel7.setVisible(false);
                setVisible(true);
    }
    
    public void getMedicine()
    {
        
          
        al=new ArrayList<String>();
        try{
            conn=new GetConnection().getConnection();
           PreparedStatement ps;
        ps=conn.prepareStatement("select name from Medicine");
            //ps=conn.PrepareStatement("select name from Medicine");
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                al.add(rs.getString("name"));
            }
        }
        catch(Exception e)
                {
                    System.out.println(e);
                }      
    }
    void getRatePerTab(javax.swing.JComboBox<String> nameComboBox,javax.swing.JTextField rateLabel)
    {
        rateLabel.setColumns(4);
        String name=(String)nameComboBox.getSelectedItem();  //name from combo box to pass in queary
        
        //for set rate
        try{
        conn=new GetConnection().getConnection();
        PreparedStatement ps;
        ps=conn.prepareStatement("select price from medicine where name=?");        
        ps.setString(1,name);
        ResultSet rs=ps.executeQuery();
        rs.next();
        String price=rs.getString("price");
        rateLabel.setText(price);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    String getTotal(javax.swing.JComboBox<String> quantityComboBox,javax.swing.JTextField rateLabel)
    {
        //if()
        //System.out.println("fix 1st print");        
        String quantitySelectedString=(String)quantityComboBox.getSelectedItem();
        int quantityInt=Integer.parseInt(quantitySelectedString);
        String priceString=rateLabel.getText(); 
        //System.out.println(priceString);
        int priceInt=Integer.parseInt(priceString);
        String finalPrice=Integer.toString(quantityInt*priceInt);
//        System.out.println("fix 2nd print");
        //showPriceLabel.setText(finalPrice);
        return finalPrice;
        
    }
    public void addNewRow(javax.swing.JPanel jPanel,javax.swing.JLabel showPriceLabel)
    {
        if(showPriceLabel.getText()!="")
        {
            jPanel.setVisible(true);            
        }
        else
        {
            //dialog box
            JOptionPane.showMessageDialog(new GenBill(), "complate previous row"); // for middle at window 

        } 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameComboBox = new javax.swing.JComboBox<>(arr);
        quantityComboBox = new javax.swing.JComboBox<>();
        nameLabel1 = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        addNewRowButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        showPriceLabel = new javax.swing.JLabel();
        rateTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        totalBillTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        nameComboBox1 = new javax.swing.JComboBox<>(arr);
        quantityComboBox1 = new javax.swing.JComboBox<>();
        nameLabel2 = new javax.swing.JLabel();
        quantityLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        addNewRowButton1 = new javax.swing.JButton();
        totalLabel1 = new javax.swing.JLabel();
        showPriceLabel1 = new javax.swing.JLabel();
        rateTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        nameComboBox3 = new javax.swing.JComboBox<>(arr);
        quantityComboBox3 = new javax.swing.JComboBox<>();
        nameLabel4 = new javax.swing.JLabel();
        quantityLabel3 = new javax.swing.JLabel();
        priceLabel3 = new javax.swing.JLabel();
        addNewRowButton3 = new javax.swing.JButton();
        totalLabel3 = new javax.swing.JLabel();
        showPriceLabel3 = new javax.swing.JLabel();
        rateTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        nameComboBox2 = new javax.swing.JComboBox<>(arr);
        quantityComboBox2 = new javax.swing.JComboBox<>();
        nameLabel3 = new javax.swing.JLabel();
        quantityLabel2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        addNewRowButton2 = new javax.swing.JButton();
        totalLabel2 = new javax.swing.JLabel();
        showPriceLabel2 = new javax.swing.JLabel();
        rateTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        nameComboBox4 = new javax.swing.JComboBox<>(arr);
        quantityComboBox4 = new javax.swing.JComboBox<>();
        nameLabel5 = new javax.swing.JLabel();
        quantityLabel4 = new javax.swing.JLabel();
        priceLabel4 = new javax.swing.JLabel();
        addNewRowButton4 = new javax.swing.JButton();
        totalLabel4 = new javax.swing.JLabel();
        showPriceLabel4 = new javax.swing.JLabel();
        rateTextField5 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Generate Bill");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        nameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(arr));
        nameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBoxActionPerformed(evt);
            }
        });

        quantityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        quantityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboBoxActionPerformed(evt);
            }
        });

        nameLabel1.setText("Name");

        quantityLabel.setText("Quantity");

        priceLabel.setText("Price");

        addNewRowButton.setText("Add");
        addNewRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRowButtonActionPerformed(evt);
            }
        });

        totalLabel.setText("Total");

        showPriceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rateTextField1.setEditable(false);
        rateTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rateTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(quantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(priceLabel)
                .addGap(18, 18, 18)
                .addComponent(rateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(addNewRowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel1)
                                .addComponent(quantityLabel)
                                .addComponent(priceLabel)
                                .addComponent(rateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addNewRowButton))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(showPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton4.setText("Genarate Bill");

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Bill");

        totalBillTextField.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton5)
                .addGap(203, 203, 203)
                .addComponent(jButton4)
                .addGap(80, 80, 80)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalBillTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jLabel8)
                    .addComponent(totalBillTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        nameComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(arr));
        nameComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBox1ActionPerformed(evt);
            }
        });

        quantityComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        quantityComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboBox1ActionPerformed(evt);
            }
        });

        nameLabel2.setText("Name");

        quantityLabel1.setText("Quantity");

        priceLabel1.setText("Price");

        addNewRowButton1.setText("Add");
        addNewRowButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRowButton1ActionPerformed(evt);
            }
        });

        totalLabel1.setText("Total");

        showPriceLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rateTextField3.setEditable(false);
        rateTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rateTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(quantityLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(priceLabel1)
                .addGap(18, 18, 18)
                .addComponent(rateTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPriceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(addNewRowButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel1)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel2)
                                .addComponent(quantityLabel1)
                                .addComponent(priceLabel1)
                                .addComponent(rateTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addNewRowButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(showPriceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        nameComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(arr));
        nameComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBox3ActionPerformed(evt);
            }
        });

        quantityComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        quantityComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboBox3ActionPerformed(evt);
            }
        });

        nameLabel4.setText("Name");

        quantityLabel3.setText("Quantity");

        priceLabel3.setText("Price");

        addNewRowButton3.setText("Add");
        addNewRowButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRowButton3ActionPerformed(evt);
            }
        });

        totalLabel3.setText("Total");

        showPriceLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rateTextField2.setEditable(false);
        rateTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(quantityLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(priceLabel3)
                .addGap(18, 18, 18)
                .addComponent(rateTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPriceLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(addNewRowButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel3)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantityComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel4)
                                .addComponent(quantityLabel3)
                                .addComponent(priceLabel3)
                                .addComponent(rateTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addNewRowButton3))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(showPriceLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        nameComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(arr));
        nameComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBox2ActionPerformed(evt);
            }
        });

        quantityComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        quantityComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboBox2ActionPerformed(evt);
            }
        });

        nameLabel3.setText("Name");

        quantityLabel2.setText("Quantity");

        priceLabel2.setText("Price");

        addNewRowButton2.setText("Add");
        addNewRowButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRowButton2ActionPerformed(evt);
            }
        });

        totalLabel2.setText("Total");

        showPriceLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rateTextField4.setEditable(false);
        rateTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(quantityLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(priceLabel2)
                .addGap(18, 18, 18)
                .addComponent(rateTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPriceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(addNewRowButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel2)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantityComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel3)
                                .addComponent(quantityLabel2)
                                .addComponent(priceLabel2)
                                .addComponent(rateTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addNewRowButton2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(showPriceLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        nameComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(arr));
        nameComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBox4ActionPerformed(evt);
            }
        });

        quantityComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        quantityComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboBox4ActionPerformed(evt);
            }
        });

        nameLabel5.setText("Name");

        quantityLabel4.setText("Quantity");

        priceLabel4.setText("Price");

        addNewRowButton4.setText("Add");
        addNewRowButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRowButton4ActionPerformed(evt);
            }
        });

        totalLabel4.setText("Total");

        showPriceLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rateTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(quantityLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(priceLabel4)
                .addGap(18, 18, 18)
                .addComponent(rateTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPriceLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(addNewRowButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel4)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantityComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel5)
                                .addComponent(quantityLabel4)
                                .addComponent(priceLabel4)
                                .addComponent(rateTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addNewRowButton4))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(showPriceLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Menu Optation");

        jMenuItem1.setText("Show Stock");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Filter Stock");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("More");

        jMenuItem2.setText("Update Stock");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboBoxActionPerformed
        // TODO add your handling code here:// for total in one row
        showPriceLabel.setText(getTotal(quantityComboBox,rateTextField1));
        
        
    }//GEN-LAST:event_quantityComboBoxActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //ComplateMedicineStock var=new ComplateMedicineStock();
        new ShowWholeStock();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //Update Stock
        new AddExistingRecord();
//        this.setVisible(false);
//        UpdateStock var=new UpdateStock();
        //RecordEantryFrame rFrame= new RecordEantryFrame();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void nameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBoxActionPerformed
        // TODO add your handling code here:
        getRatePerTab(nameComboBox,rateTextField1);
        
        
        // if no wants to function call
        
      /*         String name=(String)nameComboBox.getSelectedItem();  //name from combo box to pass in queary
        //for set rate
        try{
        conn=new GetConnection().getConnection();
        PreparedStatement ps;
        //ps=conn.PrepareStatement("select price from Medicine where name=?");
        
        //PreparedStatement ps;
        ps=conn.prepareStatement("select price from medicine where name=?");
        
        ps.setString(1,name);
        ResultSet rs=ps.executeQuery();
        rs.next();
        String price=rs.getString("price");
       
        rate.setText(price);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
        */
        
        ///same code
        
        
        /* 
        String name=(String)jComboBox1.getSelectedItem();  //name from combo box to pass in queary
        //for set rate
        try{
        conn=new GetConnection().getConnection();
        PreparedStatement ps;
        //ps=conn.PrepareStatement("select price from Medicine where name=?");
        
        //PreparedStatement ps;
        ps=conn.prepareStatement("select price from medicine where name=?");
        
        ps.setString(1,name);
        ResultSet rs=ps.executeQuery();
        rs.next();
        int price=rs.getInt("price");  
       String price1=Integer.toString(price);//convert int to string
        rate.setText(price1);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }        
       */
        
        
    }//GEN-LAST:event_nameComboBoxActionPerformed

    private void addNewRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowButtonActionPerformed
        // TODO add your handling code here:
        if(showPriceLabel.getText()!="")
        {
            jPanel4.setVisible(true);            
        }
        else
        {
            //dialog box
            JOptionPane.showMessageDialog(new GenBill(), "complate previous row"); // for middle at window 

        }
    }//GEN-LAST:event_addNewRowButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nameComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBox1ActionPerformed
        // TODO add your handling code here:
        getRatePerTab(nameComboBox1,rateTextField3);
    }//GEN-LAST:event_nameComboBox1ActionPerformed

    private void quantityComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboBox1ActionPerformed
        // TODO add your handling code here:
         showPriceLabel1.setText(getTotal(quantityComboBox1,rateTextField3));
        
    }//GEN-LAST:event_quantityComboBox1ActionPerformed

    private void addNewRowButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowButton1ActionPerformed
        // TODO add your handling code here:
                addNewRow(jPanel6,showPriceLabel1);
         
    }//GEN-LAST:event_addNewRowButton1ActionPerformed

    private void nameComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBox2ActionPerformed
        // TODO add your handling code here:
        getRatePerTab(nameComboBox2,rateTextField4);
    }//GEN-LAST:event_nameComboBox2ActionPerformed

    private void quantityComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboBox2ActionPerformed
        // TODO add your handling code here:
         showPriceLabel2.setText(getTotal(quantityComboBox2,rateTextField4));
    }//GEN-LAST:event_quantityComboBox2ActionPerformed

    private void addNewRowButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowButton2ActionPerformed
        // TODO add your handling code here:
                addNewRow(jPanel7,showPriceLabel2);

                    //jPanel7.setVisible(true);
    }//GEN-LAST:event_addNewRowButton2ActionPerformed
 
    private void nameComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBox3ActionPerformed
        // TODO add your handling code here:
        getRatePerTab(nameComboBox3,rateTextField2);
        
    }//GEN-LAST:event_nameComboBox3ActionPerformed

    private void quantityComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboBox3ActionPerformed
        // TODO add your handling code here:
         showPriceLabel3.setText(getTotal(quantityComboBox3,rateTextField2));
    }//GEN-LAST:event_quantityComboBox3ActionPerformed

    private void addNewRowButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowButton3ActionPerformed
        // TODO add your handling code here:
        addNewRow(jPanel5,showPriceLabel3);
               
    }//GEN-LAST:event_addNewRowButton3ActionPerformed

    private void nameComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBox4ActionPerformed
        // TODO add your handling code here:
        getRatePerTab(nameComboBox4,rateTextField5);
    }//GEN-LAST:event_nameComboBox4ActionPerformed

    private void quantityComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboBox4ActionPerformed
        // TODO add your handling code here:
         showPriceLabel4.setText(getTotal(quantityComboBox4,rateTextField5));
    }//GEN-LAST:event_quantityComboBox4ActionPerformed

    private void addNewRowButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRowButton4ActionPerformed
        // TODO add your handling code here:
//         if(showPriceLabel.getText()!="")
//        {
//            jPanel4.setVisible(true);            
//        }
//        else
//        {
//            //dialog box
//            JOptionPane.showMessageDialog(new GenBill(), "complate previous row"); // for middle at window 
//
//        }
         //   JOptionPane.showMessageDialog(new GenBill(), "complate previous row"); // for middle at window 
    }//GEN-LAST:event_addNewRowButton4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        FilterStock var=new FilterStock();
        //System.out.println("hi");
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void rateTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTextField3ActionPerformed

    private void rateTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewRowButton;
    private javax.swing.JButton addNewRowButton1;
    private javax.swing.JButton addNewRowButton2;
    private javax.swing.JButton addNewRowButton3;
    private javax.swing.JButton addNewRowButton4;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> nameComboBox;
    private javax.swing.JComboBox<String> nameComboBox1;
    private javax.swing.JComboBox<String> nameComboBox2;
    private javax.swing.JComboBox<String> nameComboBox3;
    private javax.swing.JComboBox<String> nameComboBox4;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JComboBox<String> quantityComboBox;
    private javax.swing.JComboBox<String> quantityComboBox1;
    private javax.swing.JComboBox<String> quantityComboBox2;
    private javax.swing.JComboBox<String> quantityComboBox3;
    private javax.swing.JComboBox<String> quantityComboBox4;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityLabel1;
    private javax.swing.JLabel quantityLabel2;
    private javax.swing.JLabel quantityLabel3;
    private javax.swing.JLabel quantityLabel4;
    private javax.swing.JTextField rateTextField1;
    private javax.swing.JTextField rateTextField2;
    private javax.swing.JTextField rateTextField3;
    private javax.swing.JTextField rateTextField4;
    private javax.swing.JTextField rateTextField5;
    private javax.swing.JLabel showPriceLabel;
    private javax.swing.JLabel showPriceLabel1;
    private javax.swing.JLabel showPriceLabel2;
    private javax.swing.JLabel showPriceLabel3;
    private javax.swing.JLabel showPriceLabel4;
    private javax.swing.JTextField totalBillTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel totalLabel2;
    private javax.swing.JLabel totalLabel3;
    private javax.swing.JLabel totalLabel4;
    // End of variables declaration//GEN-END:variables
}